name: Validate JSONs

on: [push]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate Magics JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: magics_data.schema.json
          INPUT_JSONS: magics_data.json
      - name: Validate Herbs JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: herbs_data.schema.json
          INPUT_JSONS: herbs_data.json
      - name: Validate Keys JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: magic_keys.schema.json
          INPUT_JSONS: magic_keys.json